apiVersion: apps/v1
kind: Deployment
metadata:
  name: scribble-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scribble-operator
  template:
    metadata:
      labels:
        name: scribble-operator
    spec:
      serviceAccountName: scribble-operator
      containers:
        - name: scribble-operator
          image: objectiser/scribble-operator:0.1.0
          ports:
          - containerPort: 60000
            name: metrics
          args: ["start"]
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "scribble-operator"
